# Generated by Django 4.2 on 2024-04-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarshiip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('eligibity', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('completion_time', models.CharField(max_length=10)),
                ('funding_status', models.CharField(choices=[('option1', 'Fully funded'), ('option2', 'Partially funded'), ('option3', 'Underfunded'), ('option4', 'Unfunded'), ('option5', 'Self-funded')], max_length=50)),
                ('closing_date', models.CharField(max_length=50)),
                ('degree', models.CharField(choices=[('option1', 'Fully funded'), ('option2', 'Partially funded'), ('option3', 'Underfunded'), ('option4', 'Unfunded'), ('option5', 'Self-funded')], max_length=50)),
                ('course_Abbrevistion', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('applicats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
