# Generated by Django 4.2 on 2024-04-25 11:32

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('eligibity', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('completion_time', models.DateField()),
                ('closing_date', models.DateField()),
                ('funding_status', models.CharField(choices=[('option1', 'Fully funded'), ('option2', 'Partially funded'), ('option3', 'Underfunded'), ('option4', 'Unfunded'), ('option5', 'Self-funded')], max_length=50)),
                ('degree', models.CharField(choices=[('option1', 'Phd'), ('option2', 'Diploma'), ('option3', 'Masters'), ('option4', 'Bachelor')], max_length=50)),
                ('course_Abbreviation', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('sponsor', models.CharField(default='', max_length=50)),
                ('sponsor_Image', models.ImageField(null=True, upload_to=scholarships.models.upload_location)),
                ('applicants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
