# Generated by Django 4.2 on 2024-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
