# Generated by Django 4.2 on 2024-04-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scholarshiip',
            new_name='Scholarship',
        ),
    ]
