# Generated by Django 4.2 on 2024-04-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarship_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='tag',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='tags',
            field=models.ManyToManyField(related_name='scholarships', to='scholarships.tag'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='degree',
            field=models.CharField(choices=[('Phd', 'Phd'), ('Diploma', 'Diploma'), ('Masters', 'Masters'), ('Bachelor', 'Bachelor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='funding_status',
            field=models.CharField(choices=[('Fully funded', 'Fully funded'), ('Partially funded', 'Partially funded'), ('Underfunded', 'Underfunded'), ('Unfunded', 'Unfunded'), ('Self-funded', 'Self-funded')], max_length=50),
        ),
    ]
