# Generated by Django 4.2 on 2024-04-21 14:21

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_rename_scholarshiip_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='applicats',
            new_name='applicants',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='course_Abbrevistion',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='course_Abbreviation',
            field=models.CharField(default='n', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='sponsor',
            field=models.CharField(default='n', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='sponsor_Image',
            field=models.ImageField(null=True, upload_to=scholarships.models.upload_location),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='closing_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='completion_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='degree',
            field=models.CharField(choices=[('option1', 'Phd'), ('option2', 'Diploma'), ('option3', 'Masters'), ('option4', 'Bachelor')], max_length=50),
        ),
    ]
