# Generated by Django 4.2 on 2024-04-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_remove_scholarship_tag_scholarship_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University',
            new_name='Universitie',
        ),
    ]
