# Generated by Django 4.2 on 2024-05-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_remove_universitie_university_scholarship_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitie',
            old_name='webpag1',
            new_name='webpage1',
        ),
    ]
