# Generated by Django 4.2 on 2024-05-17 07:15

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_rename_webpag1_universitie_webpage1'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitie',
            name='University_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=scholarships.models.upload_location),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='Scholarship_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=scholarships.models.upload_location2),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='University_name',
            field=models.CharField(max_length=100),
        ),
    ]
