# Generated by Django 4.2 on 2024-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_universitie_university_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='closing_date',
            field=models.DateField(default='0001-01-1'),
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='degree',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='funding_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='degree',
            field=models.CharField(default='phd', max_length=100),
            preserve_default=False,
        ),
    ]
