# Generated by Django 4.2 on 2024-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='University_name',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='course_Abbreviation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibity',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
