# Generated by Django 4.2 on 2024-06-02 13:44

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_alter_scholarship_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='land_mark',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=scholarships.models.upload_location4),
        ),
    ]
