# Generated by Django 4.2 on 2024-06-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_scholarship_land_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
