# Generated by Django 4.2 on 2024-05-03 13:23

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_alter_guide_name_alter_scholarship_university_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='sponsor_Image',
        ),
        migrations.AddField(
            model_name='universitie',
            name='University_Scholarship_image',
            field=models.ImageField(null=True, upload_to=scholarships.models.upload_location),
        ),
    ]
