# Generated by Django 4.2 on 2024-06-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_scholarship_country_code_scholarship_phone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='land_mark',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='phone_code',
        ),
    ]
