# Generated by Django 4.2 on 2024-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_remove_scholarship_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
