# Generated by Django 4.2 on 2024-05-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_remove_scholarship_sponsor_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='degree',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='degree',
            field=models.ManyToManyField(related_name='scholarships', to='scholarships.degree'),
        ),
    ]
