# Generated by Django 4.2 on 2024-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_alter_scholarship_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='application',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='available_subjects',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='benefits',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='degree_level',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligible_criteria',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligible_nationality',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
