# Generated by Django 4.2 on 2024-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_degree_remove_scholarship_degree_scholarship_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='completion_time',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='course_Abbreviation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='sponsor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
