# Generated by Django 4.2 on 2024-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0011_remove_scholarship_completion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='completion_time',
            field=models.DateField(blank=True, default='2024-05-04'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='University_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='applicants',
            field=models.IntegerField(default=0),
        ),
    ]
