# Generated by Django 4.2 on 2024-05-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0012_scholarship_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='completion_time',
            field=models.DateField(blank=True, default='0001-01-01'),
        ),
    ]
