# Generated by Django 4.2 on 2024-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_alter_scholarship_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='completion_time',
            field=models.DateField(blank=True, default='0001-01-1'),
        ),
    ]
