# Generated by Django 4.2 on 2024-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0013_alter_scholarship_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='application',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='available_subjects',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='benefits',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='degree_level',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligible_criteria',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
