# Generated by Django 4.2 on 2024-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0014_alter_scholarship_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='eligible_nationality',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
