# Generated by Django 4.2 on 2023-12-31 20:43

from django.db import migrations, models
import scholarships.models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0014_alter_scholarship_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='Scholarship_image',
            field=models.ImageField(blank=True, null=True, upload_to=scholarships.models.upload_location2),
        ),
    ]
