# Generated by Django 4.2 on 2024-06-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0015_alter_scholarship_eligible_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='application',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
