# Generated by Django 4.2 on 2024-06-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0017_scholar_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scholar_liked',
        ),
    ]
