# Generated by Django 4.2 on 2024-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0018_delete_scholar_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
