# Generated by Django 4.2 on 2024-06-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0020_alter_scholarship_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='applicants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
