# Generated by Django 4.2 on 2024-06-08 15:47

import countries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('phone_code', models.CharField(max_length=10)),
                ('country_code', models.CharField(max_length=10)),
                ('land_mark', models.ImageField(blank=True, max_length=500, null=True, upload_to=countries.models.upload_location4)),
            ],
        ),
    ]
