# Generated by Django 4.2 on 2024-06-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_details_land_mark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_details',
            name='land_mark_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
