# Generated by Django 4.2 on 2024-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_subject_subject'),
        ('accounts', '0003_alter_account_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='career_goal',
            field=models.CharField(blank=True, choices=[('Art,Design or Fasion', 'Art,Design or Fasion'), ('Beauty or Cosmetology', 'Beauty or Cosmetology'), ('Marketing, Business or Management', 'Marketing, Business or Management'), ('Computers, IT or Techinology', 'Computers, IT or Techinology'), ('Culinary Arts', 'Culinary Arts'), ('Health Care ,Nursing', 'Health Care ,Nursing'), ('Law,Criminal Justice', 'Law,Criminal Justice'), ('Teaching / Education', 'Teaching / Education')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='courses.subject'),
        ),
    ]
