# Generated by Django 4.2 on 2024-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_career_goal_alter_account_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='field_of_study',
        ),
        migrations.AddField(
            model_name='account',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
