# Generated by Django 4.2 on 2024-05-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('scholarship', models.CharField(max_length=50)),
                ('universities_offering', models.CharField(max_length=50)),
                ('jobs', models.CharField(max_length=50)),
                ('cost', models.CharField(choices=[('option1', 'Fully funded'), ('option2', 'Partially funded'), ('option3', 'Underfunded'), ('option4', 'Unfunded'), ('option5', 'Self-funded')], max_length=50)),
                ('degree', models.CharField(choices=[('option1', 'Phd'), ('option2', 'Diploma'), ('option3', 'Masters'), ('option4', 'Bachelor')], max_length=50)),
                ('course_Abbreviation', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('Eligibility', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
