# Generated by Django 4.2 on 2024-04-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_detail',
            name='name',
        ),
    ]
