# Generated by Django 4.2 on 2024-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_consultations', models.CharField(max_length=50)),
                ('professionals', models.CharField(max_length=50)),
            ],
        ),
    ]
